version: '3'

services:

  backapp:
      build:
          context: .
          dockerfile: back.Dockerfile
      image: backapp
      ports:
          - "${PORT}:${PORT}"
      environment:
          NODE_ENV: production
          SERVE_CLIENT: "${SERVE_CLIENT:-true}"
          PORT: "${PORT:-5000}"
      volumes:
          - "${IMAGES_PATH:-./images}:/usr/src/app/images"
